### ISSUE TITLE
Postinstall build failure

### ISSUE THREAD

**Issue by jaydenseric** [BitGo/unspents#15]
For some reason, [this package builds post-install](https://github.com/BitGo/unspents/blob/0.5.1/package.json#L12). Today the build fails:

```
> @bitgo/unspents@0.5.0 postinstall [redacted]/node_modules/@bitgo/unspents
> npm run build


> @bitgo/unspents@0.5.0 build [redacted]/node_modules/@bitgo/unspents
> tsc --project tsconfig.build.json

src/dimensions.ts:331:5 - error TS2352: Conversion of type 'Dictionary<DimProperty>' to type 'IDimensions' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Dictionary<DimProperty>' is missing the following properties from type 'IDimensions': nInputs, nOutputs, plus, times, and 9 more.

331     _.fromPairs(_.map(Dimensions.meta.props, (prop, key) =>
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
332       [key, func((dim as any)[key], key as keyof IDimensions, prop as DimPropertyConstructor)],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
333     )) as IDimensions,
    ~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @bitgo/unspents@0.5.0 build: `tsc --project tsconfig.build.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @bitgo/unspents@0.5.0 build script.
```

The main files are not published to npm: https://unpkg.com/@bitgo/unspents@0.5.1/dist/index.js

All of typescript is being installed in consumer projects as a dependency: https://github.com/BitGo/unspents/blob/0.5.1/package.json#L47

[This adds 41.9 MB to the `node_modules`](https://packagephobia.now.sh/result?p=typescript)!

I can't think of a valid reason for building post install, instead of pre publish. To support installation as a Git dependency, use the `prepare` script instead.

**Comment by jaydenseric** [comment]
It looks like this may have been fixed via https://github.com/BitGo/unspents/commit/1454c85fafd71508fa2c6ebb9af4ab3dd5b098af

But you guys pin all your dependencies in `@bitgo` packages, so people using the latest version of `bitgo` don't get the fix! https://github.com/BitGo/BitGoJS/blob/4.49.0/package.json#L38

Proving my point here: https://github.com/BitGo/unspents/pull/14#issuecomment-478398369

**Comment by OttoAllmendinger** [comment]
@jaydenseric thanks for your input, we're working on a fix for this

**Comment by tedkimzikto** [comment]
any updates on this our?

**Comment by OttoAllmendinger** [comment]
@tedkimzikto the issue is fixed in https://github.com/BitGo/unspents/pull/14. You also need to use the most recent version of BitGoJS.

**Comment by you-fail-me** [comment]
@OttoAllmendinger Hi, I've just updated to BitGoJS#4.49.1 and the issue still stands for me. Am I doing something wrong?

**Comment by jaydenseric** [comment]
@you-fail-me for some reason [v4.49.1](https://github.com/BitGo/BitGoJS/releases/tag/4.49.1) has been released, but not published to npm: https://github.com/BitGo/BitGoJS/issues/293

**Comment by you-fail-me** [comment]
@jaydenseric @OttoAllmendinger I've noticed that, so pointed package.json to github instead of npm (git://github.com/BitGo/BitGoJS.git#4.49.1) but still getting the issue. Any clues?

**Comment by OttoAllmendinger** [comment]
Unfortunately it seems that this package currently cannot be used as git dependency. I'm working on a fix for that. 

I recommend downgrading to `4.48` in the meantime.

**Comment by you-fail-me** [comment]
@OttoAllmendinger Thanks! Actually I was using 4.31.0 for a while, but suddenly it started breaking when I did a fresh npm install, after that I've found this issue.

Right now I've tried to use 4.48, as you've recommended and I'm having the same issue. So seems like atm I don't have a way to build BitGoJS at all, unless I have old `node_modules`, built before the issue popped up... Do you have anything to advice?

**Comment by OttoAllmendinger** [comment]
@you-fail-me can you give me the output of `npm install bitgo@4.48.1` ?

**Comment by you-fail-me** [comment]
@OttoAllmendinger the install itself works, it's the postinstall build failing, exactly like OP describes, same message. When I'm packaging a service:
```
yarn install --frozen-lockfile --non-interactive failed with code 1
warning bitgo > superagent-proxy > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning assert@0.4.9: The engine "ender" appears to be invalid.
error .../node_modules/@bitgo/unspents: Command failed.
Exit code: 2
Command: npm run build
Arguments: 
Directory: .../node_modules/@bitgo/unspents
Output:
> @bitgo/unspents@0.5.0 build .../node_modules/@bitgo/unspents
> tsc --project tsconfig.build.json

src/dimensions.ts(331,5): error TS2352: Conversion of type 'Dictionary<DimProperty>' to type 'IDimensions' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Dictionary<DimProperty>' is missing the following properties from type 'IDimensions': nInputs, nOutputs, plus, times, and 9 more.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @bitgo/unspents@0.5.0 build: `tsc --project tsconfig.build.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @bitgo/unspents@0.5.0 build script.
```

**Comment by OttoAllmendinger** [comment]
I think you might have a stale version of `bitgo` in your `node_modules` then. Version `4.48.1` does not have the `@bitgo/unspents` dependency, and I can't think of a way how it could get included transitively. Please try `rm -r node_modules/@bitgo node_modules/bitgo` and try again.

**Comment by you-fail-me** [comment]
@OttoAllmendinger Thanks a lot. Indeed, in my current case I had 4.49 sneaking in, so older versions are ok

**Comment by christiansaiki** [comment]
When do you guys plan to release the new version of bitgo in npm?
Thanks in advance

**Comment by OttoAllmendinger** [comment]
@christiansaiki the fix should arrive within the day (Pacific Time)

**Comment by OttoAllmendinger** [comment]
4.49.1 has been released

@jaydenseric we'll look the problem caused by pinned dependencies
